// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzzswsbdthbsaapmilbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6enN3c2JkdGhic2FhcG1pbGJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDk3OTgsImV4cCI6MjA3MDU4NTc5OH0.V80Fhe8LTP02q6hhiASoWubPJ2Upli2lArqQeiam69s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});